<?php

namespace Dml\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmissionRepository extends EntityRepository
{
    public function getLast()
    {
        $qb = $this->createQueryBuilder('e')
            ->orderBy('e.datePublication', 'DESC')
            ->setMaxResults(2)
        ;

        return $qb->getQuery()->getResult();
    }
}
