<?php

namespace Dml\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GallerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GallerieRepository extends EntityRepository
{
	public function getGalleries($nombreParPage, $page)
	{
		if ((int) $page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		$query = $this->createQueryBuilder('g')
                  ->orderBy('g.dateAjout', 'DESC')
                  ->getQuery();

	    $query->setFirstResult(($page-1) * $nombreParPage)
	          ->setMaxResults($nombreParPage);

	    return new Paginator($query);
	}
}
