<?php

namespace Dml\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends EntityRepository
{
    public function getSelectList()
    {
        $qb = $this->createQueryBuilder('l')
                             ->where('l.publication = 1');

        return $qb;
    }

    public function getLivres($nombreParPage, $page, $categorie, $fonction)
    {
        if ((int) $page < 1) {
            throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
        }

        $query = $this->createQueryBuilder('l')
            ->where('l.categorie = :categorie', 'l.fonction = :fonction')
            ->orderBy('l.datePublication', 'DESC')
            ->getQuery();
        $query->setParameter('categorie', $categorie);
        $query->setParameter('fonction', $fonction);

        $query->setFirstResult(($page-1) * $nombreParPage)
            ->setMaxResults($nombreParPage);

        return new Paginator($query);
    }

    public function getLast($fonction, $categorie)
    {
        $query = $this->createQueryBuilder('l')
            ->where('l.categorie = :categorie', 'l.fonction = :fonction')
            ->orderBy('l.datePublication', 'DESC')
            ->setMaxResults(2)
            ->getQuery();
        $query->setParameter('categorie', $categorie);
        $query->setParameter('fonction', $fonction);

        return $query->getResult();
    }
}
