security:
    encoders:
        Dml\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_PROFESSIONNEL:       ROLE_USER
        ROLE_ADMIN:               ROLE_PROFESSIONNEL
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /accueil
                invalidate_session: false
            provider: main
            remember_me:
                key: %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # temporaire normalement, doit etre a ROLE_PROFESSIONNEL
        # - { path: ^/espace-professionnel, roles: ROLE_PROFESSIONNEL }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
